name: Fetch API Data

on:
  schedule:
    - cron: '* * * * *'  # runs every minute

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch data from API
      run: |
        curl https://api.coingecko.com/api/v3/coins/crypto-com-chain -o data.json

    - name: Commit and push if it changed
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Automated fetch from API at $timestamp" || exit 0
        git push
